allowBuilds:
  '@nestjs/core': true
  bcrypt: true
  canvas: true
  msgpackr-extract: true
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: true
